<?= $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <?= $this->headTitle() ?>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.min.css">
        <style>
            body {
                padding-top: 75px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/css/main.css">

        <?= $this->headLink() . PHP_EOL ?>
        <?= $this->headStyle() . PHP_EOL ?>
        <?= $this->headScript() . PHP_EOL ?>
        <script src="http://www.project.dev:35729/livereload.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="container">
			<div class="navbar navbar-default" role="navigation">
		        <div class="container-fluid">
		            <div class="navbar-header">
		              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		                <span class="sr-only">Toggle navigation</span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		                <span class="icon-bar"></span>
		              </button>
		              <a class="navbar-brand" href="/">Blog</a>
		             </div>
		             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      			<?php 
			      			$this->navigation()->menu()->setPartial(array('partial/navigation.phtml','Core'))  . PHP_EOL; 
			      			echo $this->navigation()->menu()->render();
			      			?>
			    	 </div><!-- /.navbar-collapse -->
		        </div>
	        </div>
        
        	<div class="row">
        		
                <div class="col-lg-12">
                	<ol class="breadcrumb">
		             <?php
		              foreach (explode('\\', $this->navigation()->breadcrumbs()->setMinDepth(0)->setRenderInvisible(true)->setSeparator('\\')) as $bc) {
							echo "<li>$bc</li>";
					  }
		             ?>
		            </ol>
    			</div>
                
        	</div>
            <div class="row">
                <div class="col-lg-12">
		             <?= $this->layout()->content ?>
    			</div>
            </div>
        </div>

        <?php $this->inlineScript()->prependFile('/assets/jquery/dist/jquery.min.js', 'text/javascript')?>
        <?php $this->inlineScript()->appendFile('/assets/bootstrap/dist/js/bootstrap.min.js', 'text/javascript')?>
        <?php $this->inlineScript()->appendFile('/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js', 'text/javascript')?>
        <?php $this->inlineScript()->appendFile('/assets/tinymce/tinymce.min.js', 'text/javascript')?>
        
        <?= $this->inlineScript() . PHP_EOL ?>
        <!-- build:js scripts/main.min.js -->
        <script src="/js/main.js"></script>
        <script type="text/javascript">
        $(document).ready(function(){
            $('a.dropdown-toggle').append("<span class='caret'></span>");
            $('a').tooltip();
            tinymce.init({
                selector: "textarea"
             });
        });
        
        </script>
        <!-- Built with love using Web Starter Kit -->
    </body>
</html>
